# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/marshall/Documents/ECE3110_Project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/marshall/Documents/ECE3110_Project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marshall/Documents/ECE3110_Project/CMakeFiles /home/marshall/Documents/ECE3110_Project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marshall/Documents/ECE3110_Project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named opencv_example

# Build rule for target.
opencv_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opencv_example
.PHONY : opencv_example

# fast build rule for target.
opencv_example/fast:
	$(MAKE) -f CMakeFiles/opencv_example.dir/build.make CMakeFiles/opencv_example.dir/build
.PHONY : opencv_example/fast

#=============================================================================
# Target rules for targets named capture_rate

# Build rule for target.
capture_rate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 capture_rate
.PHONY : capture_rate

# fast build rule for target.
capture_rate/fast:
	$(MAKE) -f CMakeFiles/capture_rate.dir/build.make CMakeFiles/capture_rate.dir/build
.PHONY : capture_rate/fast

captureRate.o: captureRate.cpp.o

.PHONY : captureRate.o

# target to build an object file
captureRate.cpp.o:
	$(MAKE) -f CMakeFiles/capture_rate.dir/build.make CMakeFiles/capture_rate.dir/captureRate.cpp.o
.PHONY : captureRate.cpp.o

captureRate.i: captureRate.cpp.i

.PHONY : captureRate.i

# target to preprocess a source file
captureRate.cpp.i:
	$(MAKE) -f CMakeFiles/capture_rate.dir/build.make CMakeFiles/capture_rate.dir/captureRate.cpp.i
.PHONY : captureRate.cpp.i

captureRate.s: captureRate.cpp.s

.PHONY : captureRate.s

# target to generate assembly for a file
captureRate.cpp.s:
	$(MAKE) -f CMakeFiles/capture_rate.dir/build.make CMakeFiles/capture_rate.dir/captureRate.cpp.s
.PHONY : captureRate.cpp.s

opencv_example.o: opencv_example.cpp.o

.PHONY : opencv_example.o

# target to build an object file
opencv_example.cpp.o:
	$(MAKE) -f CMakeFiles/opencv_example.dir/build.make CMakeFiles/opencv_example.dir/opencv_example.cpp.o
.PHONY : opencv_example.cpp.o

opencv_example.i: opencv_example.cpp.i

.PHONY : opencv_example.i

# target to preprocess a source file
opencv_example.cpp.i:
	$(MAKE) -f CMakeFiles/opencv_example.dir/build.make CMakeFiles/opencv_example.dir/opencv_example.cpp.i
.PHONY : opencv_example.cpp.i

opencv_example.s: opencv_example.cpp.s

.PHONY : opencv_example.s

# target to generate assembly for a file
opencv_example.cpp.s:
	$(MAKE) -f CMakeFiles/opencv_example.dir/build.make CMakeFiles/opencv_example.dir/opencv_example.cpp.s
.PHONY : opencv_example.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... opencv_example"
	@echo "... capture_rate"
	@echo "... captureRate.o"
	@echo "... captureRate.i"
	@echo "... captureRate.s"
	@echo "... opencv_example.o"
	@echo "... opencv_example.i"
	@echo "... opencv_example.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

